### ISSUE TITLE
[Bug]: Cannot create new account (selfhosted)

### ISSUE THREAD

**Issue by DenuxPlays** [sussy-code/smov#22]
### What happened?

When I try to create a new account on my selfhosted instance I get the following error:
![image](https://github.com/sussy-code/smov/assets/83671398/d26cbf86-3d75-4b10-88f2-95db498af0e0)

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Create a new instance (using docker)
2. Try to create a new account

### Other relevant information

Docker compose file:
```yaml
services:
  frontend:
    image: ghcr.io/sussy-code/smov:latest
    environment:
      TMDB_READ_API_KEY: ${TMDB_READ_API_KEY}
      CORS_PROXY_URL: ${CORS_PROXY_URL}
      BACKEND_URL: ${BACKEND_URL}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8855:80"
    depends_on:
      - backend
      - proxy

  proxy:
    image: ghcr.io/sussy-code/sudo-proxy:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8856:3000"

  backend:
    image: ghcr.io/sussy-code/backend:latest
    restart: unless-stopped
    environment:
      MWB_POSTGRES__CONNECTION: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      MWB_CRYPTO__SESSION_SECRET: ${SESSION_SECRET}
      MWB_META__NAME: ${META_NAME}
      MWB_SERVER__CORS: ${SERVER_CORS}
      MWB_SERVER__ALLOW_ANY_SITE: "true"
      MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
      MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true"
    ports:
      - "127.0.0.1:8857:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} || exit 1'" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres-data: ~
```
