### ISSUE TITLE
[Feature]: Publish images to ghcr for frontend sussy-code/smov for easier docker-compose setup

### ISSUE THREAD

**Issue by jo-chemla** [sussy-code/smov#26]
### What feature do you want to add?

With movie-web, it was possible to design a docker-compose setup pointing to the ghcr build image of the movie-web frontend itself, as well as the backend and proxy - see below. It would be great to have access to a build of `sussy-code/smov` the `sussy-code/smov docker image for the frontend, the same way it is done for the backend and proxy for the other 2 sussy-code repos.

```yaml
 movieweb-frontend:
   image: ghcr.io/movie-web/movie-web 
   container_name: movieweb-frontend
   image: ghcr.io/movie-web/movie-web 
   ports:
     - 80:80
   volumes: 
     - /movieweb/config.js:/usr/share/nginx/html/config.js
   restart: always
```

### Why do you want to have this feature?

Some configurations require installing git on host and portainer container or result in the error `exec: "git": executable file not found in $PATH`. Using a container image for the frontend would resolve that problem.
