### ISSUE TITLE
[Bug]: Frontend docker doesn't work

### ISSUE THREAD

**Issue by Mubelotix** [sussy-code/smov#32]
### What happened?

Jun 02 21:31:12 nuc systemd[1]: Started movie_web.service - movie_web.
Jun 02 21:31:13 nuc docker-compose[513112]: Creating network "movie_web_default" with the default driver
Jun 02 21:31:13 nuc docker-compose[513112]: Building movieweb
Jun 02 21:31:13 nuc docker-compose[513166]: unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: fatal: couldn't find remote ref master
Jun 02 21:31:13 nuc docker-compose[513166]: : exit status 128
Jun 02 21:31:13 nuc docker-compose[513112]: Service 'movieweb' failed to build : Build failed

**Comment by Mubelotix** [comment]
It doesn't make much sense to me. 

This is what didn't work:

```docker
version: "3.8"
 
services:
 
  movieweb:
    build:
      context: https://github.com/sussy-code/smov.git
      # args:
      #   TMDB_READ_API_KEY: ""
      #   CORS_PROXY_URL: ""
      #   BACKEND_URL: ""
    ports:
      - "80:80"
    restart: unless-stopped
```

And I fixed it by using

```
version: "3.8"
 
services:
  
  movieweb:
    image: ghcr.io/sussy-code/smov:latest
    environment:
      TMDB_READ_API_KEY: "redacted"
      CORS_PROXY_URL: "{{ movie_web_proxy_domains[0] }}"
      # BACKEND_URL: ""
    ports:
      - "{{ movie_web_inner_port }}:80"
    restart: unless-stopped
```

Maybe we can just edit [the doc](https://docs.sudo-flix.lol/client/deploy#method-3-docker-compose-home-network) for now
