### ISSUE TITLE
[Feature]: AMOLED theme

### ISSUE THREAD

**Issue by userkace** [sussy-code/smov#5]
### What feature do you want to add?

Add AMOLED theming for those who have AMOLED devices!

### Why do you want to have this feature?

To enrich the viewing experiences on said devices!

### Any other details to share?

viva sudo-flix

**Comment by userkace** [comment]
Here's my implementation of the css for my fork [film.kace.dev](https://github.com/userkace/film.kace.dev)

```css
.theme-amoled {
     --colors-themePreview-primary: 30 30 30;
     --colors-themePreview-secondary: 20 20 20;
     --colors-pill-background: 0 0 0;
     --colors-pill-backgroundHover: 15 15 15;
     --colors-pill-highlight: 134 134 134;
     --colors-pill-activeBackground: 30 30 30;
     --colors-global-accentA: 134 134 134;
     --colors-global-accentB: 100 100 100;
     --colors-lightBar-light: 20 20 20;
     --colors-buttons-toggle: 69 76 212;
     --colors-buttons-toggleDisabled: 44 44 44;
     --colors-buttons-secondary: 30 30 30;
     --colors-buttons-secondaryHover: 30 30 30;
     --colors-buttons-purple: 41 45 134;
     --colors-buttons-purpleHover: 51 58 190;
     --colors-buttons-cancel: 44 44 44;
     --colors-buttons-cancelHover: 60 60 60;
     --colors-background-main: 0 0 0;
     --colors-background-secondary: 0 0 0;
     --colors-background-secondaryHover: 0 0 0;
     --colors-background-accentA: 0 0 0;
     --colors-background-accentB: 0 0 0;
     --colors-modal-background: 21 21 21;
     --colors-type-logo: 130 136 254;
     --colors-type-text: 124 124 124;
     --colors-type-dimmed: 124 124 124;
     --colors-type-divider: 44 44 44;
     --colors-type-secondary: 107 107 107;
     --colors-type-link: 130 136 254;
     --colors-type-linkHover: 170 175 255;
     --colors-search-background: 0 0 0;
     --colors-search-hoverBackground: 0 0 0;
     --colors-search-focused: 0 0 0;
     --colors-search-placeholder: 102 102 102;
     --colors-search-icon: 102 102 102;
     --colors-search-text: 255 255 255;
     --colors-mediaCard-hoverBackground: 10 10 10;
     --colors-mediaCard-hoverAccent: 124 124 124;
     --colors-mediaCard-hoverShadow: 14 14 14;
     --colors-mediaCard-shadow: 10 10 10;
     --colors-mediaCard-barColor: 84 84 84;
     --colors-mediaCard-barFillColor: 130 136 254;
     --colors-mediaCard-badge: 10 10 10;
     --colors-mediaCard-badgeText: 107 107 107;
     --colors-largeCard-background: 30 30 30;
     --colors-largeCard-icon: 51 58 190;
     --colors-dropdown-background: 10 10 10;
     --colors-dropdown-altBackground: 10 10 10;
     --colors-dropdown-hoverBackground: 40 40 40;
     --colors-dropdown-text: 124 124 124;
     --colors-dropdown-secondary: 102 102 102;
     --colors-dropdown-border: 30 30 30;
     --colors-dropdown-contentBackground: 15 15 15;
     --colors-authentication-border: 30 30 30;
     --colors-authentication-inputBg: 10 10 10;
     --colors-authentication-inputBgHover: 40 40 40;
     --colors-authentication-wordBackground: 40 40 40;
     --colors-authentication-copyText: 102 102 102;
     --colors-authentication-copyTextHover: 141 141 141;
     --colors-settings-sidebar-activeLink: 20 20 20;
     --colors-settings-sidebar-badge: 14 14 14;
     --colors-settings-sidebar-type-secondary: 79 79 79;
     --colors-settings-sidebar-type-inactive: 124 124 124;
     --colors-settings-sidebar-type-icon: 124 124 124;
     --colors-settings-sidebar-type-iconActivated: 90 98 235;
     --colors-settings-sidebar-type-activated: 170 175 255;
     --colors-settings-card-border: 30 30 30;
     --colors-settings-card-background: 30 30 30;
     --colors-settings-card-altBackground: 30 30 30;
     --colors-settings-saveBar-background: 21 21 21;
     --colors-utils-divider: 60 60 60;
     --colors-errors-card: 21 21 21;
     --colors-errors-border: 44 44 44;
     --colors-errors-type-secondary: 107 107 107;
     --colors-about-circle: 44 44 44;
     --colors-about-circleText: 141 141 141;
     --colors-editBadge-bg: 44 44 44;
     --colors-editBadge-bgHover: 49 49 49;
     --colors-editBadge-text: 141 141 141;
     --colors-progress-background: 141 141 141;
     --colors-progress-preloaded: 141 141 141;
     --colors-progress-filled: 90 98 235;
     --colors-video-buttonBackground: 84 84 84;
     --colors-video-autoPlay-background: 30 30 30;
     --colors-video-autoPlay-hover: 44 44 44;
     --colors-video-scraping-card: 10 10 10;
     --colors-video-scraping-loading: 90 98 235;
     --colors-video-scraping-noresult: 107 107 107;
     --colors-video-audio-set: 90 98 235;
     --colors-video-context-background: 17 17 17;
     --colors-video-context-light: 124 124 124;
     --colors-video-context-border: 37 37 37;
     --colors-video-context-hoverColor: 37 37 37;
     --colors-video-context-buttonFocus: 44 44 44;
     --colors-video-context-flagBg: 44 44 44;
     --colors-video-context-inputBg: 37 37 37;
     --colors-video-context-buttonOverInputHover: 44 44 44;
     --colors-video-context-inputPlaceholder: 84 84 84;
     --colors-video-context-cardBorder: 30 30 30;
     --colors-video-context-slider: 141 141 141;
     --colors-video-context-sliderFilled: 90 98 235;
     --colors-video-context-buttons-list: 30 30 30;
     --colors-video-context-buttons-active: 17 17 17;
     --colors-video-context-closeHover: 24 24 24;
     --colors-video-context-type-secondary: 84 84 84;
     --colors-video-context-type-accent: 90 98 235
}
```
